export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.status(200).json({
    surfaces: {
      "tennis_atp_miami_open": { name: "Miami Open", surface: "Hard", speed: "Medium-Fast", note: "Miami's hard courts play slightly slower than most hard court events. Heavy topspin and baseline consistency are rewarded. Big servers still have an edge but rallies run longer than at the US Open." },
      "tennis_wta_miami_open": { name: "Miami Open", surface: "Hard", speed: "Medium-Fast", note: "Miami hard courts favor aggressive baseliners with heavy topspin. High humidity can slow the ball in early rounds. Sabalenka just won Indian Wells and arrives as the clear favorite at 35.4% per Tennis Abstract simulations." },
      "tennis_atp_french_open": { name: "French Open", surface: "Clay", speed: "Slow", note: "Roland Garros clay neutralizes big servers and rewards endurance, topspin, and defensive retrieval. Alcaraz and Nadal-style players thrive here. Hard court specialists often fall short in later rounds." },
      "tennis_wta_french_open": { name: "French Open", surface: "Clay", speed: "Slow", note: "Clay at Roland Garros rewards heavy topspin, patience, and elite fitness. Swiatek is the dominant force on this surface. Points are longer, serve advantages shrink, and fitness becomes the deciding factor deep in draws." },
      "tennis_atp_wimbledon": { name: "Wimbledon", surface: "Grass", speed: "Fast", note: "Wimbledon grass is the fastest surface in tennis. Big servers dominate, points are short, and net rushers have a natural advantage. Baseline specialists often struggle to adapt from clay." },
      "tennis_wta_wimbledon": { name: "Wimbledon", surface: "Grass", speed: "Fast", note: "Grass at Wimbledon rewards flat hitting, serve power, and net aggression. Rybakina is the standout performer on this surface. Clay court specialists frequently exit early." },
      "tennis_atp_us_open": { name: "US Open", surface: "Hard", speed: "Medium", note: "US Open DecoTurf hard courts play faster than Miami. Night conditions with cool air amplify serve speed. Power hitters and big servers do well but the surface suits all-round hard court players." },
      "tennis_wta_us_open": { name: "US Open", surface: "Hard", speed: "Medium", note: "Flushing Meadows rewards aggression and power. The fast DecoTurf surface is the most consistent hard court on the WTA tour and suits players with big serves and flat groundstrokes." },
    },
    atp: {
      // Elo rankings from Tennis Abstract as of March 16, 2026
      // Alcaraz #1 (2290 Elo), Sinner #2 (2285), Djokovic #3 (2100), Zverev #4 (2060), Medvedev #5 (2030), De Minaur #6 (2024), Auger-Aliassime #7 (1999), Shelton #8 (1996), Fritz #9 (1983)
      "Alcaraz": { eloRank: 1, elo: 2290, style: "All-court attacker", strengths: "Drop shots, net presence, elite athleticism on all surfaces", miamiNote: "Won Miami 2022 and 2023. His movement, variety, and ability to dictate from any position make him the most dangerous player in the draw on hard courts.", surfaceNote: { hard: "Elite on hard — won Miami twice and is always a title threat.", clay: "Exceptional on clay — Roland Garros champion, most complete clay court player active.", grass: "Strong on grass — Wimbledon champion, adapts seamlessly to surface changes." } },
      "Sinner": { eloRank: 2, elo: 2285, style: "Aggressive baseliner", strengths: "Devastating two-handed backhand, elite return game, exceptional fitness", miamiNote: "Arrives at Miami as the tournament favorite at 41.2% per Tennis Abstract simulations after winning Indian Wells. His flat, penetrating groundstrokes are ideally suited to Miami's medium-fast courts.", surfaceNote: { hard: "The best hard court player in the world right now. Won Indian Wells and Australian Open in 2026.", clay: "Very solid on clay but not dominant — Alcaraz and Swiatek-level players match him better here.", grass: "Good on grass but not his peak surface." } },
      "Djokovic": { eloRank: 3, elo: 2100, style: "Counter-punching baseliner", strengths: "Return of serve, mental toughness, defensive retrieval, all-surface adaptability", miamiNote: "Has an excellent Miami record historically but schedule management and age (38) are now real factors. When motivated he remains the best defensive player on tour.", surfaceNote: { hard: "All-time great on hard courts — 10 Australian Open titles, 4 US Opens.", clay: "Exceptional on clay — Roland Garros champion, runner-up to Nadal many times.", grass: "The greatest Wimbledon champion in history. 7 titles." } },
      "Zverev": { eloRank: 4, elo: 2060, style: "Power baseliner", strengths: "Serve, forehand, clay court baseline game", miamiNote: "Inconsistent at Miami despite his ranking. His serve is a weapon but his footwork and net approach are less polished on hard courts than on clay.", surfaceNote: { hard: "Capable of winning hard court titles but inconsistent. Better on clay.", clay: "Strong on clay — Roland Garros finalist and a genuine threat.", grass: "Below his ranking — grass exposes his footwork limitations." } },
      "Medvedev": { eloRank: 5, elo: 2030, style: "Defensive baseliner", strengths: "Return game, flat low-bouncing groundstrokes, mental resilience", miamiNote: "Hard courts are clearly his best surface. His flat game plays well on medium-fast Miami courts and his return stats rank among the best on tour.", surfaceNote: { hard: "Elite on hard — US Open champion, multiple Australian Open finals.", clay: "Noticeably weaker on clay. Has lost to lower-ranked players at Roland Garros.", grass: "Below par on grass. Tends to exit early at Wimbledon." } },
      "De Minaur": { eloRank: 6, elo: 2024, style: "Counter-punching speedster", strengths: "Elite footwork, retrieval, slice backhand, fitness", miamiNote: "A legitimate dangerous floater. His elite speed and counter-punching style neutralizes power players and he has the fitness to win five-set matches on hard courts.", surfaceNote: { hard: "His best surface — his speed and retrieval are maximized on hard.", clay: "Competitive but not elite on clay. His counter-punching still works.", grass: "Good on grass — his speed translates well to net approaches." } },
      "Auger-Aliassime": { eloRank: 7, elo: 1999, style: "Serve-and-volley attacker", strengths: "Serve, net play, indoor hard court dominance", miamiNote: "Strong serve-and-volley game works on Miami's hard courts. Tennis Abstract analysis highlights his exceptional indoor hard court record in particular.", surfaceNote: { hard: "Strong on hard — his serve and net game are most effective here.", clay: "Below his ranking on clay.", grass: "Natural grass court player — good at Wimbledon." } },
      "Shelton": { eloRank: 8, elo: 1996, style: "Power server, aggressive attacker", strengths: "Serve, left-handed advantages, net presence", miamiNote: "Dangerous on US hard courts. His left-handed serve creates unusual angles and his aggressive style suits Miami's medium-fast surface.", surfaceNote: { hard: "Most effective on hard courts — his serve is the biggest weapon in these conditions.", clay: "Less effective on clay — his game is suited to faster surfaces.", grass: "Solid on grass — his serve is even more effective." } },
      "Fritz": { eloRank: 9, elo: 1983, style: "Big server, aggressive baseliner", strengths: "Serve, forehand, US hard court expertise", miamiNote: "A legitimate title threat at Miami. His powerful serve regularly pushes 140mph and his forehand can overpower opponents. Comfortable on US hard courts.", surfaceNote: { hard: "Strong on US hard courts — this is where he wins titles.", clay: "Below his ranking on clay.", grass: "Solid on grass — his serve plays well." } },
      "Musetti": { eloRank: 10, elo: 1979, style: "One-handed backhand all-court player", strengths: "One-handed backhand, clay court movement, drop shots", miamiNote: "Clay specialist who can be vulnerable on faster hard courts. His one-handed backhand is beautiful but harder to control on fast surfaces.", surfaceNote: { hard: "Below his ranking on hard courts.", clay: "Excellent on clay — his best surface by far.", grass: "Decent on grass — his one-hander can be a weapon." } },
    },
    wta: {
      // WTA Elo rankings from Tennis Abstract as of March 16, 2026
      // Sabalenka #1 (2247), Rybakina #2 (2163), Swiatek #3 (2110), Pegula #4 (2094), Gauff #5 (2074), Mboko #6 (2072), Anisimova #7 (2050), Svitolina #8 (2049), Muchova #9 (2041), Bencic #10 (1988)
      // Winners/UFE data from Tennis Abstract last 52 weeks
      "Sabalenka": { eloRank: 1, elo: 2247, style: "Power baseliner", strengths: "Serve power, forehand aggression, hard court dominance", miamiNote: "Just won Indian Wells and arrives as Miami favorite at 35.4%. Her stats back it up — 1120 winners at an 18.4% rate over the last 52 weeks, best ratio of any top player. Hard courts are her domain.", surfaceNote: { hard: "The premier hard court force in women's tennis. Won Miami 2023, won Indian Wells 2026.", clay: "Solid on clay but Swiatek neutralizes her power game.", grass: "Good on grass — her flat serve is devastating on fast surfaces." } },
      "Rybakina": { eloRank: 2, elo: 2163, style: "Power server, flat hitter", strengths: "Serve — biggest weapon in women's tennis — flat groundstrokes, composure", miamiNote: "Hard courts suit her flat hitting well. Her winners-to-UFE ratio (1.1) is among the best on tour, meaning she generates offense without giving points away.", surfaceNote: { hard: "Strong on hard — her flat serve is devastating.", clay: "Less dominant on clay — topspin players can neutralize her.", grass: "Her best surface — Wimbledon champion 2022." } },
      "Swiatek": { eloRank: 3, elo: 2110, style: "Heavy topspin baseliner", strengths: "Forehand topspin, consistency, mental strength under pressure", miamiNote: "Miami suits her game — the slightly slower hard courts play closer to her preferred clay conditions. Won Miami 2022. Her consistency metrics (17.7% winners, 20.1% UFE rate) show she can be exploited by aggressive players.", surfaceNote: { hard: "Very strong on hard but not untouchable — Sabalenka has her number here.", clay: "The greatest clay court player active — Roland Garros champion 4 times.", grass: "Weaker on grass — tends to exit earlier at Wimbledon." } },
      "Pegula": { eloRank: 4, elo: 2094, style: "Aggressive baseliner", strengths: "Forehand power, hard court consistency", miamiNote: "Hard courts are clearly her best surface. Solid winners rate (12.5%) and low UFE rate (14.6%) — she stays in rallies and creates opportunities without over-hitting.", surfaceNote: { hard: "Strong on hard courts — consistently reaches deep in major hard court events.", clay: "Competitive but clay is not her peak surface.", grass: "Below her ranking on grass." } },
      "Gauff": { eloRank: 5, elo: 2074, style: "Athletic all-court player", strengths: "Return game, athleticism, improving serve", miamiNote: "US hard courts are her best environment. Her winners/UFE ratio (0.6) is lower than elite level — she relies on getting opponents to make mistakes rather than outright winning points, which can be risky against aggressive players.", surfaceNote: { hard: "Strong on US hard courts — US Open champion 2023.", clay: "Competitive on clay but not dominant.", grass: "Below her ranking on grass — tends to struggle at Wimbledon." } },
      "Mboko": { eloRank: 6, elo: 2072, style: "Aggressive young baseliner", strengths: "Power, athleticism, emerging tour presence", miamiNote: "A rapidly rising young Canadian. Limited Miami track record at this level but her Elo rating of 2072 puts her firmly in title contention territory. Worth monitoring in the draw.", surfaceNote: { hard: "Most of her results have come on hard courts.", clay: "Still developing on clay.", grass: "Limited grass court record." } },
      "Anisimova": { eloRank: 7, elo: 2050, style: "Aggressive flat hitter", strengths: "Forehand power, serve", miamiNote: "Her stats show she generates plenty of winners (18.4% rate) but also unforced errors (23.4% rate) — she's an aggressive player who can be on or off on any given day. Dangerous draw threat.", surfaceNote: { hard: "Her best surface — her flat hitting works well on hard.", clay: "Less consistent on clay.", grass: "Capable on grass when hitting cleanly." } },
      "Svitolina": { eloRank: 8, elo: 2049, style: "Counter-punching defensive baseliner", strengths: "Consistency, retrieval, mental toughness", miamiNote: "A steady competitor who makes opponents beat her. Her UFE rate (16.2%) is low for a top-10 player, reflecting her defensive, mistake-free approach.", surfaceNote: { hard: "Solid on hard — her consistency keeps her competitive.", clay: "Good on clay — works hard for every point.", grass: "Strong on grass — has made deep Wimbledon runs." } },
      "Muchova": { eloRank: 9, elo: 2041, style: "Creative all-court player", strengths: "Variety, drop shots, net play, slice", miamiNote: "A genuinely difficult stylistic matchup for any player. Her slice, net presence, and variety create problems across all surfaces. Her UFE rate is moderate (15.2%) — she can be erratic but her upside is very high.", surfaceNote: { hard: "Effective on hard — her variety creates problems for power baseliners.", clay: "Strong on clay — Roland Garros finalist.", grass: "Good on grass — her net play is a natural fit." } },
      "Bencic": { eloRank: 10, elo: 1988, style: "All-court attacker", strengths: "One-handed backhand slice, return game, variety", miamiNote: "Best winners-to-UFE ratio in the last 52 weeks data (1.2) — she generates more winners than errors which is an elite benchmark. Returning from maternity leave but clearly playing well.", surfaceNote: { hard: "Strong on hard courts historically.", clay: "Solid on clay.", grass: "Good on grass — Olympic gold medalist 2020." } },
    }
  });
}
